name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Apache and clean web root
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl enable httpd
            sudo systemctl start httpd
            sudo rm -rf /var/www/html/*
          EOF

      - name: Upload website files to EC2
        run: |
          scp -r ./website/* ec2-user@${{ secrets.EC2_HOST }}:/tmp/
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            sudo cp -r /tmp/* /var/www/html/
            sudo chown -R apache:apache /var/www/html
            sudo systemctl restart httpd
          EOF
